{
 "title": "Jcrtp's Nimbus Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(process_virtual_memory_bytes,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - min without (node) (process_start_time_seconds{instance=\"${instance}\"})"
    }
   ]
  },
  {
   "title": "Updates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apt_upgrades_pending" }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\"}"
    }
   ]
  },
  {
   "title": "Swap Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / node_memory_SwapTotal_bytes"
    }
   ]
  },
  {
   "title": "Total Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "attached_validator_balance_total / 1000000000"
    }
   ]
  },
  {
   "title": "Earnings Percent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(attached_validator_balance{job=\"nimbus\"})/1000000000-(count(attached_validator_balance{job=\"nimbus\"} > 16)*32))/(count(attached_validator_balance{job=\"nimbus\"} > 16)*32)"
    }
   ]
  },
  {
   "title": "Validator Activity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(min without (node) (beacon_attestations_sent_total))",
     "legendFormat": "Attestations"
    },
    {
     "expr": "sum(min without (node) (beacon_blocks_proposed_total))",
     "legendFormat": "Blocks"
    }
   ]
  },
  {
   "title": "APY (via Daily)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(attached_validator_balance{job=\"nimbus\"}) - sum(attached_validator_balance{job=\"nimbus\"} offset 1d != 0) - (32 * count(attached_validator_balance{job=\"nimbus\"} > 16)) + (32 * count(attached_validator_balance{job=\"nimbus\"} offset 1d > 16)))/(32 * avg_over_time(count(attached_validator_balance{job=\"nimbus\"} > 16)[1d:])))/1000000000 * 365",
     "legendFormat": "annualized daily return"
    }
   ]
  },
  {
   "title": "Daily Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(attached_validator_balance{job=\"nimbus\"})/1000000000 - sum(attached_validator_balance{job=\"nimbus\"} offset 1d != 0)/1000000000 - (32 * count(attached_validator_balance{job=\"nimbus\"} > 16)) + (32 * count(attached_validator_balance{job=\"nimbus\"} offset 1d > 16))"
    }
   ]
  },
  {
   "title": "Nimbus CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min without (node) (rate(process_cpu_seconds_total{instance=\"${instance}\"}[$__rate_interval])) * 100"
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "4 - sum(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_cpu_frequency_max_hertz{cpu=\"0\"}"
    }
   ]
  },
  {
   "title": "Nimbus RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min without (node) (process_resident_memory_bytes{instance=\"${instance}\"})"
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "Validator Activity",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 13, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min without (node) (rate(beacon_blocks_proposed_total{instance=\"${instance}\"}[$__rate_interval])) * 48",
     "legendFormat": "Block"
    },
    {
     "expr": "(rate(beacon_attestations_sent_total{instance=\"${instance}\"}[$__rate_interval])) * 48",
     "legendFormat": "Attestation"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "400 - sum(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) * 100",
     "legendFormat": "Total"
    },
    { "expr": "100", "legendFormat": "100%" },
    {
     "expr": "min without (node) (rate(process_cpu_seconds_total{instance=\"${instance}\"}[$__rate_interval])) * 100",
     "legendFormat": "Nimbus"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total" },
    {
     "expr": "min without (node) (process_resident_memory_bytes{instance=\"${instance}\"})",
     "legendFormat": "Nimbus"
    }
   ]
  },
  {
   "title": "Attestation Delay",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 10 },
   "targets": [
    {
     "expr": "min without (node) (rate(beacon_attestation_sent_delay_bucket{instance=\"${instance}\",le=\"-4.0\"}[$__rate_interval])) * 48",
     "legendFormat": "-4"
    },
    {
     "expr": "min without (node) (rate(beacon_attestation_sent_delay_bucket{instance=\"${instance}\",le=\"-2.0\"}[$__rate_interval])) * 48",
     "legendFormat": "-2"
    },
    {
     "expr": "min without (node) (rate(beacon_attestation_sent_delay_bucket{instance=\"${instance}\",le=\"-1.0\"}[$__rate_interval])) * 48",
     "legendFormat": "-1"
    },
    {
     "expr": "min without (node) (rate(beacon_attestation_sent_delay_bucket{instance=\"${instance}\",le=\"-0.5\"}[$__rate_interval])) * 48",
     "legendFormat": "-0.5"
    },
    {
     "expr": "min without (node) (rate(beacon_attestation_sent_delay_bucket{instance=\"${instance}\",le=\"-0.1\"}[$__rate_interval])) * 48",
     "legendFormat": "-0.1"
    },
    {
     "expr": "min without (node) (rate(beacon_attestation_sent_delay_bucket{instance=\"${instance}\",le=\"-0.05\"}[$__rate_interval])) * 48",
     "legendFormat": "-0.05"
    },
    {
     "expr": "min without (node) (rate(beacon_attestation_sent_delay_bucket{instance=\"${instance}\",le=\"0.05\"}[$__rate_interval])) * 48",
     "legendFormat": "0.05"
    },
    {
     "expr": "min without (node) (rate(beacon_attestation_sent_delay_bucket{instance=\"${instance}\",le=\"0.1\"}[$__rate_interval])) * 48",
     "legendFormat": "0.1"
    },
    {
     "expr": "min without (node) (rate(beacon_attestation_sent_delay_bucket{instance=\"${instance}\",le=\"0.5\"}[$__rate_interval])) * 48",
     "legendFormat": "0.5"
    },
    {
     "expr": "min without (node) (rate(beacon_attestation_sent_delay_bucket{instance=\"${instance}\",le=\"1.0\"}[$__rate_interval])) * 48",
     "legendFormat": "1"
    },
    {
     "expr": "min without (node) (rate(beacon_attestation_sent_delay_bucket{instance=\"${instance}\",le=\"2.0\"}[$__rate_interval])) * 48",
     "legendFormat": "2"
    },
    {
     "expr": "min without (node) (rate(beacon_attestation_sent_delay_bucket{instance=\"${instance}\",le=\"4.0\"}[$__rate_interval])) * 48",
     "legendFormat": "4"
    },
    {
     "expr": "min without (node) (rate(beacon_attestation_sent_delay_bucket{instance=\"${instance}\",le=\"8.0\"}[$__rate_interval])) * 48",
     "legendFormat": "8"
    }
   ]
  },
  {
   "title": "SSD Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total{device=\"sda\"}[$__rate_interval]) / rate(node_disk_writes_completed_total{device=\"sda\"}[$__rate_interval])",
     "legendFormat": "Write"
    },
    {
     "expr": "rate(node_disk_read_time_seconds_total{device=\"sda\"}[$__rate_interval]) / rate(node_disk_reads_completed_total{device=\"sda\"}[$__rate_interval])",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "MicroSD Space Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{device=\"/dev/mmcblk0p2\"} - node_filesystem_avail_bytes{device=\"/dev/mmcblk0p2\"}) / node_filesystem_size_bytes{device=\"/dev/mmcblk0p2\"}"
    }
   ]
  },
  {
   "title": "SSD Space Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{device=\"/dev/sda1\"} - node_filesystem_avail_bytes{device=\"/dev/sda1\"}) / node_filesystem_size_bytes{device=\"/dev/sda1\"}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\"}[$__rate_interval])",
     "legendFormat": "Tx"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[$__rate_interval])",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Total Net I/O",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{device=\"eth0\"}",
     "legendFormat": "Tx"
    },
    {
     "expr": "node_network_receive_bytes_total{device=\"eth0\"}",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "I/O Wait Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_pressure_io_waiting_seconds_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min without (node) (libp2p_peers{instance=\"${instance}\"})",
     "legendFormat": "libp2p peers"
    },
    {
     "expr": "min without (node) (libp2p_pubsub_peers{instance=\"${instance}\"})",
     "legendFormat": "libp2p pubsub peers"
    },
    {
     "expr": "min without (node) (nbc_peers{instance=\"${instance}\"})",
     "legendFormat": "beacon_node peers"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min without (node) (nbc_peers{instance=\"${instance}\"})"
    }
   ]
  }
 ]
}